export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS = "LOAD_AUTHORS";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_FINISHED = "API_CALL_FINISHED";